scoring/scoring/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
import scoring

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', 'scoring.views.index', name='index'),
    url(r'^scoring/(?P<competition_id>\d+)/$', 'scoring.views.competition_detail', name='competition_detail'),
    url(r'^scoring/(\d+)/event/(?P<event_id>\d+)/$', 'scoring.views.event_detail', name='event_detail'),
    url(r'^scoring/(\d+)/event/(?P<event_id>\d+)/timer/$', 'scoring.views.timer', name='timer'),
    url(r'^scoring/(\d+)/event/(?P<event_id>\d+)/station/(?P<station_num>\d+)/$', 'scoring.views.station', name='station'),
    url(r'^scoring/(\d+)/event/(?P<event_id>\d+)/station_score/(?P<station_num>\d+)/$', 'scoring.views.station_score', name='station_score'),
    url(r'^scoring/(\d+)/event/(?P<event_id>\d+)/judging/(?P<station_num>\d+)/$', 'scoring.views.judging', name='judging'),
    url(r'^api/event/(?P<pk>[0-9]+)$', 'scoring.views.json_event'),
    url(r'^api/score/(?P<event_id>\d+)/(?P<station_num>\d+)$', 'scoring.views.json_score'),
    url(r'^api/timer/(?P<pk>[0-9]+)$', 'scoring.views.json_timer'),
    url(r'^api/start_time/(?P<pk>[0-9]+)$', 'scoring.views.json_start_time'),
)

scoring/competitions/models.py
from django.db import models

class Competition(models.Model):
    name = models.CharField(max_length=200)
    location = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __unicode__(self):
        return unicode(self.name)

class Athlete(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    BELL_WEIGHT_CHOICES = (
        (6.0, '6kg'),
        (8.0, '8kg'),
        (10.0, '10kg'),
        (12.0, '12kg'),
        (16.0, '16kg'),
        (20.0, '20kg'),
        (24.0, '24kg'),
        (28.0, '28kg'),
        (32.0, '32kg'),
    )
    WEIGHT_DIVISION_CHOICES = (
        #MALE & FEMALE
        ('up to 53kg',  'up to 53kg'),
        ('up to 58kg',  'up to 58kg'),
        ('up to 63kg',  'up to 63kg'),
        ('up to 68kg',  'up to 68kg'),
        #FEMALE ONLY
        ('over 63kg',   'over 63kg'),
        ('over 68kg',   'over 68kg'),
        #MALE ONLY
        ('up to 73kg',  'up to 73kg'),
        ('up to 78kg',  'up to 78kg'),
        ('up to 85kg',  'up to 85kg'),
        ('up to 95kg',  'up to 95kg'),
        ('over 95kg',   'over 95kg'),
        ('up to 105kg', 'up to 105kg'),
        ('over 105kg',  'over 105kg'),
    )
    AGE_CLASS_CHOICES = (
        ('men', 'Men'),
        ('women', 'Women'),
        ('youth', 'Youth'),
        ('junior', 'Junior'),
        ('masters', 'Masters'),
        ('team', 'Team'),
    )
    name = models.CharField(max_length=200)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    weight = models.FloatField()
    weight_class = models.CharField(max_length=200, choices=WEIGHT_DIVISION_CHOICES)
    age_class = models.CharField(max_length=200, choices=AGE_CLASS_CHOICES)
    apparatus_weight = models.FloatField(choices=BELL_WEIGHT_CHOICES)

    def __unicode__(self):
        return unicode(self.name)

class Judge(models.Model):
    name = models.CharField(max_length=200)

    def __unicode__(self):
        return unicode(self.name)

class Event(models.Model):
    EVENT_TYPE_CHOICES = (
        ('biathlon-jerk', 'Biathlon Jerk'),
        ('biathlon-snatch', 'Biathlon Snatch'),
        ('longcycle', 'Long Cycle'),
        ('snatch', 'Snatch Only'),
        ('combined-snatch', 'Snatch'),
        ('oalc', 'OALC'),
        ('chairpress', 'Chair Press Relay'),
    )
    competition = models.ForeignKey(Competition, default=1)
    name = models.CharField(max_length=200)
    scheduled_start_datetime = models.DateTimeField(verbose_name="Scheduled Start")
    duration_seconds = models.IntegerField(default=600) # 10 minutes
    event_type = models.CharField(max_length=200, choices=EVENT_TYPE_CHOICES)
    timer = models.CharField(max_length=5, default='00:00')
    start_time = models.IntegerField(default=0)
    countdown_duration = models.IntegerField(default=0)

    def __unicode__(self):
        return unicode(self.name)

    def competition_name(self):
        return self.competition.name

    @property
    def sorted_scoringstation_set(self):
        return self.scoringstation_set.order_by('station_num', 'athlete__gender', 'athlete__weight_class', 'athlete__apparatus_weight', 'score')

    @property
    def duration_minutes(self):
        secs = self.duration_seconds
        mins, secs = divmod(secs, 60)
        hours, mins = divmod(mins, 60)
        return '%02d:%02d' % (mins, secs)

    @property
    def current_event_id(self):
        if self.event_locations.all().count() > 0:
            current_event = self.event_locations.all()[0].current_event
            if current_event:
                return current_event.id
            else:
                return -1
        else:
            return -1

class EventLocation(models.Model):
    name = models.CharField(max_length=200)
    events = models.ManyToManyField(Event, blank=True, related_name='event_locations')
    current_event = models.ForeignKey(Event, blank=True, null=True, related_name='current_event')

    def __unicode__(self):
        return unicode(self.name)

class ScoringStation(models.Model):
    station_num = models.IntegerField()
    athlete = models.ForeignKey(Athlete)
    judge = models.ForeignKey(Judge)
    event = models.ForeignKey(Event)
    score = models.IntegerField(default=0)

    def __unicode__(self):
        return unicode('Athlete: {} - Score: {} - Judge: {} - Station: {}'.format(
            self.athlete.name, self.score, self.judge.name, self.station_num))

scoring/scoring/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.context_processors import csrf
from django.core.exceptions import ObjectDoesNotExist

from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from competitions.serializers import EventSerializer, ScoringStationSerializer, EventTimerSerializer, EventStartTimeSerializer
from competitions.models import Competition, Event, ScoringStation

def index(request):
    competition_list = Competition.objects.order_by('-start_date')[:5]
    context = {'competition_list': competition_list}
    return render(request, 'scoring/index.html', context)

def competition_detail(request, competition_id):
    competition = get_object_or_404(Competition, pk=competition_id)
    return render(request, 'scoring/competition_detail.html', {'competition': competition})

#def events(request, competition_id):
#    return HttpResponse("You're looking at the events of competition %s." % competition_id)

def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'scoring/event_detail.html', {'event': event})

def timer(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'scoring/event_timer.html', {'event': event})

def station(request, event_id, station_num):
    event = get_object_or_404(Event, pk=event_id)
    try:
        scoring_station = event.scoringstation_set.get(station_num=station_num)
#        return render(request, 'scoring/station_detail.html', {'scoring_station': scoring_station})
        return render(request, 'scoring/station_card.html', {'scoring_station': scoring_station})
    except ObjectDoesNotExist:
        return render(request, 'scoring/not_in_use.html', {'event_name': event.name, "current_event_id": event.current_event_id, 'station_num': station_num, 'target': 'station'})

def station_score(request, event_id, station_num):
    event = get_object_or_404(Event, pk=event_id)
    scoring_station = event.scoringstation_set.get(station_num=station_num)
    #scoring_station = get_object_or_404(ScoringStation, pk=scoring_station_id)
    return render(request, 'scoring/station_score2.html', {'scoring_station': scoring_station})

def judging(request, event_id, station_num):
    event = get_object_or_404(Event, pk=event_id)
    scoring_station = event.scoringstation_set.get(station_num=station_num)
    #scoring_station = get_object_or_404(ScoringStation, pk=scoring_station_id)
    context = {'scoring_station': scoring_station}
    context.update(csrf(request))
    return render(request, 'scoring/judging.html', context)

@api_view(['GET'])
def json_event(request, pk):
    if request.method == 'GET':
        event = Event.objects.get(pk=pk)
        serializer = EventSerializer(event)
        return Response(serializer.data)

@api_view(['GET', 'POST'])
def json_timer(request, pk, format=None):
    try:
        event = Event.objects.get(pk=pk)
    except Event.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = EventTimerSerializer(event)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = EventTimerSerializer(event, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'POST'])
def json_score(request, event_id, station_num, format=None):
    try:
        event = get_object_or_404(Event, pk=event_id)
        scoring_station = event.scoringstation_set.get(station_num=station_num)
        #scoring_station = ScoringStation.objects.get(pk=pk)
    except ScoringStation.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = ScoringStationSerializer(scoring_station)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = ScoringStationSerializer(scoring_station, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'POST'])
def json_start_time(request, pk, format=None):
    try:
        event = Event.objects.get(pk=pk)
    except Event.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = EventStartTimeSerializer(event)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = EventStartTimeSerializer(event, data=request.DATA)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

scoring/templates/scoring/competition_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ competition.name }}</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
    <script src="/static/jquery-2.0.3.min.js"></script>
    <script language="JavaScript">
        $(document).ready(function() {
            setTimeout(function() {
                window.location.reload(1);
            }, 20000);
            $(window).load(function() {
                var w = $(window);
                var row = $('#current_event');
                if (row.length) {
                    var pos = row.offset().top - (w.height()/2);
                    var body = $("body, html");
                    body.animate({scrollTop:pos}, '2000');
                }
            });
        });
    </script>
</head>
<body class="comp-text">

    <div id="header">
        <div id="header-inner">
            <h2>Competition - {{ competition.name }}</h2>
            <table class="header">
                <tr><td>Location:</td><td>{{ competition.location}}</td></tr>
                <tr><td>Start date:</td><td>{{ competition.start_date }}</td></tr>
                <tr><td>End date:</td><td>{{ competition.end_date }} minutes</td></tr>
            </table>
        </div>
    </div>

    <h2></h2>
    <table id="competitions" class="content">
        <thead>
            <tr>
                <th>Event</th>
                <th>Scheduled Start</th>
                <th>Event Type</th>
            </tr>
        </thead>
        {% for event in competition.event_set.all %}
        {% if event.id == event.current_event_id %}
        <tr id="current_event">
        {% else %}
        <tr>
        {% endif %}
            {% if event.id == event.current_event_id %}
            <td>&#10148; <a href="event/{{ event.id }}/">{{ event.name }}</a></td>
            {% else %}
            <td><a href="event/{{ event.id }}/">{{ event.name }}</a></td>
            {% endif %}
            <td>{{ event.scheduled_start_datetime }}</td>
            <td>{{ event.get_event_type_display }}</td>
        </tr>
        <tr>
            <td>
                <table>
                    <tr>
                        <th>Station</th>
                        <th>Athlete</th>
                        <th>Score</th>
                        <th>Weight Class</th>
                        <th>Bell Weight</th>
                    </tr>
                    {% for scoring_station in event.sorted_scoringstation_set.all %}
                    <tr>
                        <td>{{ scoring_station.station_num }}</td>
                        <td>{{ scoring_station.athlete.name }}</td>
                        <td>{{ scoring_station.score}}</td>
                        <td>{{ scoring_station.athlete.weight_class}}</td>
                        <td>{{ scoring_station.athlete.get_apparatus_weight_display}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div>

</body>
</html>

scoring/templates/scoring/event_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ event.name }}</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body class="comp-text">
    <div id="header">
        <div id="header-inner">
            <h2>Event - {{ event.name }}</h2>
            <table class="header">
                <tr><td>Location:</td><td>{{ event.location}}</td></tr>
                <tr><td>Scheduled start:</td><td>{{ event.scheduled_start_datetime }}</td></tr>
                <tr><td>Duration:</td><td>{{ event.duration_minutes }} minutes</td></tr>
            </table>
        </div>
    </div>

    <h2>Scoring Stations</h2>
        <table class="content">
        <tr>
            <th>Station</th>
            <th>Athlete</th>
            <th>Score</th>
            <th>Weight Class</th>
            <th>Bell Weight</th>
            <th>Judge</th>
            <th style="text-align: center;">Spectator</th>
            <th style="text-align: center;">Timing</th>
            <th style="text-align: center;">Judging</th>
            <th style="text-align: center;">Score</th>
        </tr>
        {% for scoring_station in event.sorted_scoringstation_set.all %}
        <tr>
            <td>{{ scoring_station.station_num }}</td>
            <td>{{ scoring_station.athlete.name }}</td>
            <td>{{ scoring_station.score}}</td>
            <td>{{ scoring_station.athlete.weight_class}}</td>
            <td>{{ scoring_station.athlete.get_apparatus_weight_display}}</td>
            <td>{{ scoring_station.judge.name }}</td>
            <td style="text-align: center;"><a href="station/{{ scoring_station.station_num }}/"><img src="/static/search.png" height="20px" /></a></td>
            <td style="text-align: center;"><a href="timer/"><img src="/static/search.png" height="20px" /></a></td>
            <td style="text-align: center;"><a href="judging/{{ scoring_station.station_num }}/"><img src="/static/search.png" height="20px" /></a></td>
            <td style="text-align: center;"><a href="station_score/{{ scoring_station.station_num }}/"><img src="/static/search.png" height="20px" /></a></td>
        </tr>
        {% endfor %}
        </table>

    <div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div>

</body>
</html>

scoring/templates/scoring/event_timer.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ event.name }}</title>
    <script src="/static/jquery-2.0.3.min.js"></script>
    <script src="/static/scoring.js"></script>
    <script language="JavaScript">
        $(document).ready(function() {
            $(window).load(function() {
                doCenter();
            });
            $(window).resize(function() {
                doCenter();
            });
            // To initially run the centering function:
            $(window).load();
        });
        setInterval(function(){ getTimer({{event.id}}, {{event.current_event_id}}, false) }, 250);
    </script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>

<header>
    <div class="athlete-name">{{ event.name }}</div>
</header>

<body class="comp-text">

    <div id="timer-large" class="timer-large comp-text">00:00</div>

    <!-- div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div -->

</body>
</html>

scoring/templates/scoring/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Kettlebell Competitions</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body class="comp-text">

    <div id="header">
        <div id="header-inner">
            <h1>Kettlebell Competitions</h1>
        </div>
    </div>

{% if competition_list %}
    <ul>
    {% for competition in competition_list %}
        <li><a href="/scoring/{{ competition.id }}/">{{ competition.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No competitions are available.</p>
{% endif %}

    <div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div>

</body>
</html>

scoring/templates/scoring/judging.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ scoring_station }}</title>
    <script src="/static/jquery-2.0.3.min.js"></script>
    <script src="/static/moment.js"></script>
    <script src="/static/scoring.js"></script>
    <script language="JavaScript">
        var stationNum = {{scoring_station.station_num}};
        $(document).ready(function(){
            $(window).load(function(){
                doCenter();
            });
            $(window).resize(function(){
                doCenter();
            });
            $(document).keydown(function(e) {
                if ( stationNum == 1 && e.keyCode == '32' ) {
                    // Space Bar - Only station #1 can start/stop the timer
                    startOrStopTimer();
                }
                else if (e.keyCode == '39') {
                    // Right cursor key
                    incrementScore();
                }
                else if (e.keyCode == '37') {
                    // Left cursor key
                    decrementScore();
                }
                else if (e.keyCode == '82' && !e.metaKey ) {
                    // 'r'... as long as Command key is not also typed
                    resetScore();
                    if (e.shiftKey) {
                        document.getElementById("timer").innerHTML = '00:00';
                        postTimer();
                    }
                }
            });
            // To initially run the centering and getScore functions:
            $(window).load();

            // Judging stations call getTimer only to check for "event" assignment changes
            setInterval(function(){getTimer({{scoring_station.event.id}}, stationNum, true)}, 250);
        });
        function decrementScore() {
            // Get value from element on the page:
            var score = parseInt(document.getElementById("score").innerHTML);
            score--;

            updateAndPostScore(score);
        }
        function incrementScore() {
            // Get value from element on the page:
            var score = parseInt(document.getElementById("score").innerHTML);
            score++;

            updateAndPostScore(score);
        }
        function updateAndPostScore(score) {
            // update local view
            document.getElementById("score").innerHTML = score + "";
            doCenter();

            // Send the current score using post
            var data = {
                id: {{scoring_station.id}},
                score: score,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            };
            var posting = $.post( '/api/score/{{scoring_station.event.id}}/{{scoring_station.station_num}}', data );
        }
        function postTimer() {
            // Get values from elements on the page:
            var timer = document.getElementById("timer").innerHTML;

            // Send the data using post
            var data = {
                id: {{scoring_station.event.id}},
                timer: timer,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            };

            var posting = $.post( '/api/timer/{{scoring_station.event.id}}', data );
        }
        function resetScore() {
            // Send reset data using post
            var data = {
                id: {{scoring_station.id}},
                score: 0,
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            };

            var posting = $.post( '/api/score/{{scoring_station.event.id}}/{{scoring_station.station_num}}', data );

            // Reset local view
            document.getElementById("score").innerHTML = '0';
            doCenter();
        }

        var myCounter = null;
        var eventStarted = false;
        var countdownStarted = 0;
        var initialCountdown = 0;
        var eventTimer = null;
        var seconds = 0;

        function startOrStopTimer() {
            if ( countdownStarted == 1 ) {
                stopCountdown();
            }
            else {
                countdownStarted = 1;
                seconds = 10; // initial countdown for lifters before actual lift countdown starts
                document.getElementById("timer").innerHTML = moment(moment.duration(seconds*1000).minutes(), "mm").format("mm") + ":" + moment(moment.duration(seconds*1000).seconds(), "ss").format("ss");
                postTimer();
                initialCountdown = 1;
                document.getElementById("beep-long").play();
                eventTimer = setInterval(function(){ countdown() }, 1000);
            }
        }

        function stopCountdown() {
            clearInterval(eventTimer);
            countdownStarted = 0;
        }

        function countdown() {
            seconds = seconds - 1;
            document.getElementById("timer").innerHTML = moment(moment.duration(seconds*1000).minutes(), "mm").format("mm") + ":" + moment(moment.duration(seconds*1000).seconds(), "ss").format("ss");
            postTimer();

            if (seconds == 0) {
                stopCountdown();
                document.getElementById("beep-long").play();
            }
            else if (seconds <= 3 && initialCountdown == 1) {
                document.getElementById("beep-short").play();
            }
            else if (seconds == {{scoring_station.event.duration_seconds}}) {
                document.getElementById("beep-long").play();
            }

            if (seconds == 1 && initialCountdown == 1) {
                seconds = seconds + {{scoring_station.event.duration_seconds}}; // add event duration time
                initialCountdown = 0;
            }
        }

    </script>
    <audio id="beep-short" src="/static/beep-short.mp3" preload="auto"></audio>
    <audio id="beep-long" src="/static/beep-long.mp3" preload="auto"></audio>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body class="comp-text">

    <form>{% csrf_token %}</form>

    <div id="header">
        <div id="header-inner">
            <h2>
                Event: {{ scoring_station.event.name }}<br />
            </h2>

            <h3>
                Scoring Station &#x2799; {{ scoring_station.station_num }}<br />
                Judge: {{ scoring_station.judge.name }}<br />
                Athlete: {{ scoring_station.athlete.name }}
            </h3>
        </div>
    </div>

    <div id="score" class="score">{{ scoring_station.score }}</div>

    <div id="timer" class="timer">00:00</div>

    <div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div>

</body>
</html>

scoring/templates/scoring/not_in_use.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ scoring_station }}</title>
    <script src="/static/jquery-2.0.3.min.js"></script>
    <script src="/static/scoring.js"></script>
    <script language="JavaScript">
        $(document).ready(function(){
            $(window).load(function(){
                doCenter();
            });
            $(window).resize(function(){
                doCenter();
            });
            // To initially run the centering function:
            $(window).load();

            setInterval(function(){checkForNextEvent()}, 3000);
        });

        function checkForNextEvent() {
            var current_event_id = {{ current_event_id }};
            var station_num = {{ station_num }};
            var target = "{{ target }}";

            // setup a redirect
            var currentPath = document.location.pathname;

            //                               comp     evt       stn
            // Spectator URL example: /scoring/1/event/1/station/1/
            // Timing URL example:    /scoring/1/event/1/timer/
            // Judging URL example:   /scoring/1/event/1/judging/1/

            var newURL = window.location.protocol + "//" + window.location.host;
            var pathArray = currentPath.split( '/' );

            newURL += "/" + pathArray[1];       // 'scoring'
            newURL += "/" + pathArray[2];       // <competition id>
            newURL += "/" + pathArray[3];       // 'event'
            newURL += "/" + current_event_id;   // <event_id>
            newURL += "/" + target;

            if ( target != "timer" ) {
                 newURL += "/" + station_num;
            }

            window.location.href = newURL;
        }
    </script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body class="comp-text">

    <div id="header">
        <div id="header-inner">
            <h2>
                Event: {{ event_name }}<br />
                Station: {{ station_num }}<br />
            </h2>
        </div>
    </div>

    <div id="score" class="na comp-text">Waiting for next event.</div>

</body>
</html>

scoring/templates/scoring/station_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ scoring_station }}</title>
    <script src="/static/jquery-2.0.3.min.js"></script>
    <script src="/static/scoring.js"></script>
    <script language="JavaScript">
        $(document).ready(function(){
            $(window).load(function(){
                doCenter();
            });
            $(window).resize(function(){
                doCenter();
            });
            // To initially run the centering function:
            $(window).load();
            setInterval(function(){ getScoreAndTiming({{ scoring_station.event.id }}, {{ scoring_station.station_num }}) }, 250);
        });
    </script>
    <link rel="stylesheet" type="text/css" href="/static/style.css">
</head>
<body class="comp-text">

    <div id="header">
        <div id="header-inner">
            <h2>
                Event: {{ scoring_station.event.name }}<br />
            </h2>

            <h3>
                Viewing Station &#x2799; {{ scoring_station.station_num }}<br />
                Judge: {{ scoring_station.judge.name }}<br />
                Athlete: {{ scoring_station.athlete.name }}
            </h3>
        </div>
    </div>

    <div id="score" class="score">{{ scoring_station.score }}</div>

    <div id="timer" class="timer">00:00</div>

    <div id="footer">
        <div id="footer-inner">
            <img style="position:absolute;right:20px;height:100px;" src="/static/logosc.jpg" />
        </div>
    </div>

</body>
</html>